version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # MySQL root 用户密码
      MYSQL_DATABASE: nacos      # 创建名为 nacos 的数据库
      MYSQL_DATABASE_XXL_JOB: xxl_job  # 创建名为 xxl_job 的数据库
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql        # 持久化 MySQL 数据
    networks:
      - nacos_network

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      MODE: standalone                  # 单机模式运行 Nacos
      SPRING_DATASOURCE_PLATFORM: mysql  # 指定数据源为 MySQL
      MYSQL_SERVICE_HOST: mysql          # MySQL 服务地址
      MYSQL_SERVICE_DB_NAME: nacos       # Nacos 使用的数据库名称
      MYSQL_SERVICE_PORT: 3306          # MySQL 服务端口
      MYSQL_SERVICE_USER: root          # MySQL 用户名
      MYSQL_SERVICE_PASSWORD: root  # MySQL 密码
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"  # Nacos 控制台端口
    depends_on:
      - mysql                           # 依赖 MySQL 服务
    networks:
      - nacos_network

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.0.0
    container_name: xxl-job-admin
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root'
    ports:
      - "7070:8080"  # 将本机的 7070 端口映射到容器的 8080 端口
    depends_on:
      - mysql                           # 依赖 MySQL 服务
    networks:
      - nacos_network

  valueline-api:
    image: valueline-api:latest  # 使用你构建的镜像
    container_name: valueline-api
    ports:
      - "8082:8082"  # 暴露API端口
    depends_on:
      - mysql
      - nacos  # 如果依赖nacos
    networks:
      - nacos_network
    restart: on-failure:3  # 最多重试3次

  valueline-strategy:
      image: valueline-strategy:latest
      container_name: valueline-strategy
      environment:
        # 日志配置
        LOG_PATH: "/app/logs"
      ports:
        - "9997:9998"  # XXL-JOB执行器端口
        - "20882:20881"  # Dubbo端口
      volumes:
        # 挂载日志目录（确保宿主机目录存在）
        - ./logs/valueline-strategy:/app/logs
        # 单独挂载XXL-JOB日志
        - ./logs/xxl-job:/app/logs/xxl-job
      networks:
        - nacos_network
      restart: on-failure:3  # 最多重试3次

  valueline-web:
    image: valueline-web:latest  # 使用你构建的镜像
    container_name: valueline-web
    ports:
      - "8081:8081"  # 暴露API端口
    networks:
      - nacos_network

  valueline-frontend:
    image: valueline-frontend:lates  # 使用你构建的镜像
    container_name: valueline-frontend
    ports:
      - "3000:3000"  # 暴露API端口
    networks:
      - nacos_network
volumes:
  mysql_data:                            # MySQL 数据卷

networks:
  nacos_network:                         # 自定义网络