version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # MySQL root 用户密码
      MYSQL_DATABASE: nacos      # 创建名为 nacos 的数据库
      MYSQL_DATABASE_XXL_JOB: xxl_job  # 创建名为 xxl_job 的数据库
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql        # 持久化 MySQL 数据
    networks:
      - valueline_network

  valueline-web:
    image: valueline-web:latest  # 使用你构建的镜像
    container_name: valueline-web
    ports:
      - "8081:8081"  # 暴露API端口
      - "6666:6666" # DEBUG端口
    networks:
      - valueline_network

  valueline-frontend:
    image: valueline-frontend:latest  # 使用你构建的镜像
    container_name: valueline-frontend
    ports:
      - "3000:3000"  # 暴露API端口
    networks:
      - valueline_network
volumes:
  mysql_data:                            # MySQL 数据卷

networks:
  valueline_network:                         # 自定义网络